(() => {
  const $=s=>document.querySelector(s); let token=sessionStorage.getItem('wrsAdminToken')||'';
  const api=(path,opt={})=>fetch('/.netlify/functions/'+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{}),...(token?{Authorization:'Bearer '+token}:{})}});
  const show=(logged)=>{$('#loginView').classList.toggle('hidden',logged);$('#adminView').classList.toggle('hidden',!logged)};
  async function login(){const msg=$('#loginMsg');msg.textContent='Memeriksa…';try{const r=await api('admin-auth',{method:'POST',body:JSON.stringify({password:$('#adminPassword').value})});const d=await r.json();if(!r.ok)throw Error(d.error||'Gagal login');token=d.token;sessionStorage.setItem('wrsAdminToken',token);show(true);await loadAll()}catch(e){msg.textContent=e.message}}
  async function loadSettings(){const r=await api('admin-settings');if(r.status===401)return logout();const d=await r.json();const s=d.settings||{};$('#minMag').value=String(s.minMag||4);$('#tsunamiPriority').checked=s.tsunamiPriority!==false;$('#maintenance').checked=!!s.maintenance;$('#announcement').value=s.announcement||''}
  async function saveSettings(){const msg=$('#settingsMsg');msg.textContent='Menyimpan…';const body={minMag:Number($('#minMag').value),tsunamiPriority:$('#tsunamiPriority').checked,maintenance:$('#maintenance').checked,announcement:$('#announcement').value};const r=await api('admin-settings',{method:'PUT',body:JSON.stringify(body)});const d=await r.json();msg.textContent=r.ok?'Pengaturan tersimpan.':(d.error||'Gagal menyimpan.')}
  async function health(){const r=await api('admin-health');if(r.status===401)return logout();const d=await r.json();if(!r.ok)throw Error(d.error);const q=d.latest||{};$('#metricMag').textContent=Number.isFinite(Number(q.magnitude))?'M'+Number(q.magnitude).toFixed(1):'—';$('#metricPlace').textContent=q.place||'—';$('#metricCount').textContent=d.count??'—';$('#metricSubs').textContent=d.subscriptions??'—';$('#metricStatus').textContent='ONLINE';$('#metricFetched').textContent=d.fetchedAt?new Date(d.fetchedAt).toLocaleString('id-ID'):'—';const src=d.sources||{};$('#sources').innerHTML=Object.entries(src).map(([k,v])=>`<div class="source"><b>${k}</b><span>${v} event</span></div>`).join('')}
  async function broadcast(){const msg=$('#broadcastMsg');const title=$('#broadcastTitle').value.trim(),body=$('#broadcastBody').value.trim();if(!body)return msg.textContent='Isi pesan terlebih dahulu.';if(!confirm('Kirim peringatan ke semua perangkat yang terdaftar?'))return;msg.textContent='Mengirim…';const r=await api('admin-broadcast',{method:'POST',body:JSON.stringify({title,body})});const d=await r.json();msg.textContent=r.ok?`Terkirim: ${d.sent} perangkat. Subscription dibersihkan: ${d.removed}.`:(d.error||'Gagal mengirim.')}
  async function loadAll(){try{await Promise.all([loadSettings(),health()])}catch(e){$('#settingsMsg').textContent=e.message}}
  function logout(){sessionStorage.removeItem('wrsAdminToken');token='';show(false)}
  $('#loginBtn').onclick=login;$('#adminPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#saveSettings').onclick=saveSettings;$('#refreshHealth').onclick=health;$('#broadcastBtn').onclick=broadcast;$('#logoutBtn').onclick=logout;show(!!token);if(token)loadAll();
})();
